# Generated by Django 6.0.7 on 2026-08-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Soft flag: suggests the user change their password (never blocks portal access).'),
        ),
    ]
